sudo: required

cache:
  timeout: 10000
  directories:
  - ${PWD}/.m2

services:
  - docker

# We test against InfluxDB versions from 1.6 with the most actual JDK
# and we also test the most recent InfluxDB version with LTS JDK.
env:
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.6 RUN_NIGHTLY_BINARY=true
  - MAVEN_JAVA_VERSION=3-jdk-8-slim INFLUXDB_VERSION=1.6 RUN_NIGHTLY_BINARY=true CODE_COV=true

script: ./compile-and-test.sh

jobs:
  include:
  - stage: deploy
    script: docker run -it --rm --volume ${PWD}:/usr/src/mymaven --volume ${PWD}/.m2:/root/.m2 --workdir /usr/src/mymaven maven:${MAVEN_JAVA_VERSION} mvn clean deploy -DskipTests -s config/deploy-settings.xml -U -Denv.BONITOO_SNAPSHOT_USER=${BONITOO_SNAPSHOT_USER} -Denv.BONITOO_SNAPSHOT_PASSWORD=${BONITOO_SNAPSHOT_PASSWORD}
    env: MAVEN_JAVA_VERSION=3-jdk-8-slim INFLUXDB_VERSION=1.6 RUN_NIGHTLY_BINARY=true

after_success:
  - test "true" = ${CODE_COV:=false} && bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat target/surefire-reports/*.txt
  - cat influxdb-nightly.log
  - cat influxd-nightly.log
  - cat fluxd_nightly.log
